let container = document.querySelector("#container")
let dino = document.querySelector("#dino")
let block = document.querySelector("#block")
let road = document.querySelector("#road")
let score = document.querySelector("#score")
let gameover = document.querySelector("#gameover")
